### ISSUE TITLE
🐛 Bug: 프로젝트 설명 파트 PDF 출력시 다크 모드 적용안되는 문제 

### ISSUE THREAD

**Issue by min-bok** [weniv/MAKE-RE_ver2#231]
# 🐛 Bug: 프로젝트 설명 파트 PDF 출력시 다크 모드 적용안되는 문제 #231

## 👀 문제 발생 위치 및 환경
- `src\components\templates\Project\ProjectPreview.jsx` 

## 🚨문제 발생 예측
1. `DefaultTextarea` 컴포넌트의 문제
    - 해당 컴포넌트를 포함하는 다른 컴포넌트에서는 문제가 발생하지않음 
2. `ProjectPreview.jsx` 컴포넌트의 문제

## 🛠️ 해결 내용
- `ProjectPreview.jsx` 컴포넌트 outline 클래스에 color 속성 추가
- 
    ```css
      p.outline {
        white-space: pre-wrap;
        line-height: 2rem;
        color: var(--surface-color); /** 추가된 부분 */
      }
    ```
